spring:
  application:
    name: FathersAdvice
server:
  http2:
    enabled: true
  port: 8090

logging:
  level:
    senac:
      father:
        advice: DEBUG
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'
